# Generated by Django 4.2.7 on 2023-11-27 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('reg_data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.user')),
            ],
        ),
        migrations.CreateModel(
            name='Timer_Ssesion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('datatime_start', models.DateTimeField()),
                ('timer_time', models.IntegerField()),
                ('name', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer.user')),
            ],
        ),
    ]
